runtime: custom
env: flex
entrypoint: npm start

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1
  cpu_utilization:
    target_utilization: 0.65

env_variables:
  APP_TOKEN: "MTQzNjc3OTIxMzA0OTgyMzM3Ng.Gc5Jlp.Ha-V6ZuV-281RXBEmEEz4TwXCl_lz2n-FweOao"
  GEMINI_KEY: "AIzaSyDJ5f-rPYC0tkbw_LRh13DM0MIUg5Hvm_I"
